/// Regression tests: the Dart analysis must reproduce the Python reference
/// (yolo_pose/analysis.py as-run) on saved fixtures within tolerance.
///
/// Fixtures are generated by `tools/dump_golden.py` in the reference repo
/// (numpy 2.4.4 / scipy 1.17.1 / ruptures 1.1.10; versions recorded inside
/// each fixture). Tolerances: intermediate signals and metrics rtol 1e-6
/// with atol 1e-4 px (velocities px/s); segment/phase boundaries exact.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:barbell_velocity_app/analysis/analysis_config.dart';
import 'package:barbell_velocity_app/analysis/pipeline.dart';

const rtol = 1e-6;
const atol = 1e-4;

void expectCloseList(List<double> actual, List<dynamic> expected, String label) {
  expect(actual.length, expected.length, reason: '$label: length mismatch');
  for (var i = 0; i < actual.length; i++) {
    final e = expected[i];
    if (e == null) {
      expect(actual[i].isNaN, isTrue,
          reason: '$label[$i]: expected NaN, got ${actual[i]}');
    } else {
      final ev = (e as num).toDouble();
      final tol = atol + rtol * ev.abs();
      expect((actual[i] - ev).abs(), lessThanOrEqualTo(tol),
          reason: '$label[$i]: ${actual[i]} vs $ev');
    }
  }
}

void expectCloseNum(double actual, num expected, String label) {
  final tol = atol + rtol * expected.abs();
  expect((actual - expected).abs(), lessThanOrEqualTo(tol),
      reason: '$label: $actual vs $expected');
}

void main() {
  final fixtureDir = Directory('test/fixtures');
  final files = fixtureDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.golden.json'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  test('fixtures are present', () {
    expect(files, isNotEmpty,
        reason: 'No golden fixtures found — run tools/dump_golden.py '
            'in the reference repo (see PROGRESS.md).');
  });

  for (final file in files) {
    final name = file.uri.pathSegments.last;
    group(name, () {
      final data = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
      final fps = (data['source']['fps'] as num).toDouble();
      final input = [
        for (final v in data['input_positions'] as List)
          v == null ? null : (v as num).toDouble()
      ];
      final result = analyzePositions(input, fps, config: const AnalysisConfig());

      test('clean positions match', () {
        expectCloseList(result.cleanPositions, data['clean_positions'], 'clean');
      });

      test('smoothed positions match', () {
        expectCloseList(result.smoothPositions, data['smooth_positions'], 'smooth');
      });

      test('velocities match', () {
        expectCloseList(result.rawVelocity, data['raw_velocity'], 'rawVel');
        expectCloseList(result.smoothVelocity, data['smooth_velocity'], 'smoothVel');
      });

      test('PELT segments match exactly (boundaries and flags)', () {
        final expectedSegs = data['segments'] as List;
        expect(result.segments.length, expectedSegs.length,
            reason: 'segment count');
        for (var i = 0; i < expectedSegs.length; i++) {
          final e = expectedSegs[i] as Map<String, dynamic>;
          final a = result.segments[i];
          expect(a.start, e['start'], reason: 'seg[$i].start');
          expect(a.end, e['end'], reason: 'seg[$i].end');
          expect(a.frames, e['frames'], reason: 'seg[$i].frames');
          expect(a.skippedShort, e['skipped_short'], reason: 'seg[$i].short');
          expect(a.selected, e['selected'], reason: 'seg[$i].selected');
          expect(a.merged, e['merged'], reason: 'seg[$i].merged');
          expectCloseNum(a.displacement, e['displacement'] as num, 'seg[$i].disp');
        }
      });

      test('concentric phases match exactly (ruptures + peaks)', () {
        expect([for (final (s, e) in result.phases) [s, e]],
            data['ruptures_phases'], reason: 'ruptures phases');
        expect([for (final (s, e) in result.peaksPhases) [s, e]],
            data['peaks_phases'], reason: 'peaks phases');
      });

      test('per-rep metrics match', () {
        final expectedReps = data['reps'] as List;
        expect(result.reps.length, expectedReps.length, reason: 'rep count');
        for (var i = 0; i < expectedReps.length; i++) {
          final e = expectedReps[i] as Map<String, dynamic>;
          final a = result.reps[i];
          expect(a.startFrame, e['start_frame'], reason: 'rep[$i].start');
          expect(a.endFrame, e['end_frame'], reason: 'rep[$i].end');
          expectCloseNum(a.avgVelPxS, e['avg_vel_px_s'] as num, 'rep[$i].avg');
          expectCloseNum(a.maxVelPxS, e['max_vel_px_s'] as num, 'rep[$i].max');
          expectCloseNum(a.durationS, e['duration_s'] as num, 'rep[$i].duration');
          expectCloseNum(a.displacementPx, e['displacement_px'] as num, 'rep[$i].disp');
        }
      });
    });
  }
}
